-- Phase 1: normalize collection-shaped operational data without deleting the
-- legacy columns. Existing application code can continue to use the legacy
-- columns while the triggers below keep the new tables synchronized.
--
-- The legacy columns (`activities.dates`, `registrations.guests`,
-- `leave_dates`, `leave_times`, `rejoin_times`, `cancelled_members`, and
-- `cancelled_guests`) deliberately remain in place. Do not remove them until
-- all read paths have moved to the normalized tables and a retention period
-- has elapsed.

create table if not exists public.normalization_migration_issues (
  id bigint generated by default as identity primary key,
  source_table text not null,
  source_id text not null,
  source_column text not null,
  source_value text not null,
  details text not null,
  detected_at timestamptz not null default now()
);

create unique index if not exists normalization_migration_issues_source_unique
  on public.normalization_migration_issues (source_table, source_id, source_column, source_value);

alter table public.normalization_migration_issues enable row level security;

create or replace function public.normalization_safe_date(value text)
returns date
language plpgsql
immutable
as $$
begin
  if value is null or value !~ '^\d{4}-\d{2}-\d{2}$' then
    return null;
  end if;

  return value::date;
exception
  when others then
    return null;
end;
$$;

create or replace function public.normalization_safe_timestamptz(value text)
returns timestamptz
language plpgsql
stable
as $$
begin
  if nullif(btrim(value), '') is null then
    return null;
  end if;

  return value::timestamptz;
exception
  when others then
    return null;
end;
$$;

create or replace function public.normalization_jsonb_array(value jsonb)
returns jsonb
language sql
immutable
as $$
  select case when jsonb_typeof(value) = 'array' then value else '[]'::jsonb end;
$$;

create or replace function public.normalization_jsonb_object(value jsonb)
returns jsonb
language sql
immutable
as $$
  select case when jsonb_typeof(value) = 'object' then value else '{}'::jsonb end;
$$;

create table if not exists public.activity_dates (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities(id) on delete cascade,
  activity_date date not null,
  sort_order integer not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activity_dates_activity_date_unique unique (activity_id, activity_date),
  constraint activity_dates_sort_order_check check (sort_order > 0)
);

create index if not exists activity_dates_active_date_idx
  on public.activity_dates (activity_date, activity_id)
  where is_active;

alter table public.activity_dates enable row level security;

create table if not exists public.registration_guests (
  id uuid primary key default gen_random_uuid(),
  registration_id uuid not null references public.registrations(id) on delete cascade,
  guest_position integer not null,
  display_name text null,
  gender text null,
  joined_at timestamptz null,
  paid_court boolean not null default false,
  paid_ac boolean not null default false,
  legacy_payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint registration_guests_position_unique unique (registration_id, guest_position),
  constraint registration_guests_position_check check (guest_position >= 0),
  constraint registration_guests_gender_check check (gender is null or gender in ('male', 'female', 'other'))
);

create index if not exists registration_guests_registration_idx
  on public.registration_guests (registration_id, guest_position);

alter table public.registration_guests enable row level security;

create table if not exists public.registration_cancellation_events (
  id uuid primary key default gen_random_uuid(),
  registration_id uuid not null references public.registrations(id) on delete cascade,
  legacy_source text not null,
  legacy_position integer not null,
  participant_type text not null,
  display_name text null,
  picture_url text null,
  added_by text null,
  participant_added_at timestamptz null,
  recorded_at timestamptz null,
  legacy_payload jsonb not null,
  created_at timestamptz not null default now(),
  constraint registration_cancellation_events_source_unique unique (registration_id, legacy_source, legacy_position),
  constraint registration_cancellation_events_source_check check (legacy_source in ('cancelled_members', 'cancelled_guests')),
  constraint registration_cancellation_events_participant_type_check check (participant_type in ('self', 'guest'))
);

create index if not exists registration_cancellation_events_registration_idx
  on public.registration_cancellation_events (registration_id, created_at desc);

alter table public.registration_cancellation_events enable row level security;

alter table public.registrations
  add column if not exists activity_date_id bigint null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'registrations_activity_date_id_fkey'
      and conrelid = 'public.registrations'::regclass
  ) then
    alter table public.registrations
      add constraint registrations_activity_date_id_fkey
      foreign key (activity_date_id)
      references public.activity_dates(id)
      on delete set null;
  end if;
end;
$$;

create index if not exists registrations_activity_date_active_idx
  on public.registrations (activity_date_id, created_at)
  where status = 'active' and activity_date_id is not null;

create table if not exists public.season_registration_date_statuses (
  registration_id uuid not null references public.registrations(id) on delete cascade,
  activity_date_id bigint not null references public.activity_dates(id) on delete cascade,
  is_on_leave boolean not null default false,
  leave_submitted_at timestamptz null,
  rejoined_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (registration_id, activity_date_id)
);

create index if not exists season_registration_date_statuses_date_idx
  on public.season_registration_date_statuses (activity_date_id, is_on_leave);

alter table public.season_registration_date_statuses enable row level security;

comment on table public.activity_dates is
  'Canonical activity dates. activities.dates remains a legacy compatibility snapshot during migration.';
comment on table public.registration_guests is
  'Canonical per-guest data. registrations.guests remains a legacy compatibility snapshot during migration.';
comment on table public.season_registration_date_statuses is
  'Canonical per-activity-date leave/rejoin state for season registrations.';
comment on table public.registration_cancellation_events is
  'Canonical cancellation history. legacy_payload preserves the original JSON object without reinterpretation.';

create or replace function public.sync_activity_dates_from_legacy_dates()
returns trigger
language plpgsql
as $$
begin
  -- Never delete an activity date: old attendance and pickup records may refer to it.
  -- Removing a date from the legacy JSON only retires it from future use.
  update public.activity_dates
  set is_active = false,
      updated_at = now()
  where activity_id = new.id
    and is_active;

  with raw_dates as (
    select public.normalization_safe_date(item.value) as activity_date, item.ordinality::integer as sort_order
    from jsonb_array_elements_text(public.normalization_jsonb_array(new.dates)) with ordinality as item(value, ordinality)
  ), valid_dates as (
    select activity_date, min(sort_order) as sort_order
    from raw_dates
    where activity_date is not null
    group by activity_date
  )
  insert into public.activity_dates (activity_id, activity_date, sort_order, is_active)
  select new.id, valid_dates.activity_date, valid_dates.sort_order, true
  from valid_dates
  on conflict (activity_id, activity_date) do update
  set sort_order = excluded.sort_order,
      is_active = true,
      updated_at = now();

  insert into public.normalization_migration_issues (source_table, source_id, source_column, source_value, details)
  select
    'activities',
    new.id::text,
    'dates',
    item.value,
    'Ignored by activity_dates because it is not a valid ISO date.'
  from jsonb_array_elements_text(public.normalization_jsonb_array(new.dates)) as item(value)
  where public.normalization_safe_date(item.value) is null
  on conflict (source_table, source_id, source_column, source_value) do nothing;

  return new;
end;
$$;

create or replace function public.sync_registration_guests_from_legacy_json()
returns trigger
language plpgsql
as $$
begin
  with legacy_guests as (
    select
      item.ordinality::integer - 1 as guest_position,
      nullif(btrim(item.value ->> 'name'), '') as display_name,
      case
        when item.value ->> 'gender' in ('male', 'female', 'other') then item.value ->> 'gender'
        else null
      end as gender,
      public.normalization_safe_timestamptz(item.value ->> 'added_at') as joined_at,
      case lower(coalesce(item.value ->> 'paid_court', '')) when 'true' then true when '1' then true else false end as paid_court,
      case lower(coalesce(item.value ->> 'paid_ac', '')) when 'true' then true when '1' then true else false end as paid_ac,
      item.value as legacy_payload
    from jsonb_array_elements(public.normalization_jsonb_array(new.guests)) with ordinality as item(value, ordinality)
  ), upserted_guests as (
    insert into public.registration_guests (
      registration_id,
      guest_position,
      display_name,
      gender,
      joined_at,
      paid_court,
      paid_ac,
      legacy_payload
    )
    select new.id, guest_position, display_name, gender, joined_at, paid_court, paid_ac, legacy_payload
    from legacy_guests
    on conflict (registration_id, guest_position) do update
    set display_name = excluded.display_name,
        gender = excluded.gender,
        joined_at = excluded.joined_at,
        paid_court = excluded.paid_court,
        paid_ac = excluded.paid_ac,
        legacy_payload = excluded.legacy_payload,
        updated_at = now()
    returning guest_position
  )
  delete from public.registration_guests as guest
  where guest.registration_id = new.id
    and not exists (
      select 1
      from legacy_guests
      where legacy_guests.guest_position = guest.guest_position
    );

  return new;
end;
$$;

create or replace function public.sync_registration_cancellation_events_from_legacy_json()
returns trigger
language plpgsql
as $$
begin
  delete from public.registration_cancellation_events
  where registration_id = new.id
    and legacy_source in ('cancelled_members', 'cancelled_guests');

  insert into public.registration_cancellation_events (
    registration_id,
    legacy_source,
    legacy_position,
    participant_type,
    display_name,
    picture_url,
    added_by,
    participant_added_at,
    legacy_payload
  )
  select
    new.id,
    entries.legacy_source,
    entries.ordinality::integer - 1,
    case when entries.legacy_source = 'cancelled_guests' or entries.value ? 'addedBy' then 'guest' else 'self' end,
    nullif(btrim(entries.value ->> 'name'), ''),
    nullif(btrim(entries.value ->> 'image'), ''),
    nullif(btrim(entries.value ->> 'addedBy'), ''),
    public.normalization_safe_timestamptz(entries.value ->> 'time'),
    entries.value
  from (
    select 'cancelled_members'::text as legacy_source, item.value, item.ordinality
    from jsonb_array_elements(public.normalization_jsonb_array(new.cancelled_members)) with ordinality as item(value, ordinality)
    union all
    select 'cancelled_guests'::text as legacy_source, item.value, item.ordinality
    from jsonb_array_elements(public.normalization_jsonb_array(new.cancelled_guests)) with ordinality as item(value, ordinality)
  ) as entries;

  return new;
end;
$$;

create or replace function public.sync_registration_activity_date_reference()
returns trigger
language plpgsql
as $$
begin
  new.activity_date_id := null;

  if new.activity_id is null or new.activity_date is null then
    return new;
  end if;

  select activity_date.id
  into new.activity_date_id
  from public.activity_dates as activity_date
  where activity_date.activity_id = new.activity_id
    and activity_date.activity_date = public.normalization_safe_date(new.activity_date)
  limit 1;

  return new;
end;
$$;

create or replace function public.sync_season_registration_date_statuses_from_legacy()
returns trigger
language plpgsql
as $$
begin
  if new.activity_id is null or new.activity_date is not null then
    return new;
  end if;

  -- A rejoin removes the date from leave_dates. Preserve the event row but
  -- reset its current state before applying the current leave list below.
  update public.season_registration_date_statuses
  set is_on_leave = false,
      updated_at = now()
  where registration_id = new.id
    and is_on_leave;

  with raw_dates as (
    select leave_date as source_date, true as is_on_leave, null::timestamptz as leave_submitted_at, null::timestamptz as rejoined_at
    from unnest(coalesce(new.leave_dates, '{}'::text[])) as leave_date

    union all

    select entry.key, false, public.normalization_safe_timestamptz(entry.value), null::timestamptz
    from jsonb_each_text(public.normalization_jsonb_object(new.leave_times)) as entry(key, value)

    union all

    select entry.key, false, null::timestamptz, public.normalization_safe_timestamptz(entry.value)
    from jsonb_each_text(public.normalization_jsonb_object(new.rejoin_times)) as entry(key, value)
  ), normalized_dates as (
    select
      public.normalization_safe_date(source_date) as activity_date,
      bool_or(is_on_leave) as is_on_leave,
      max(leave_submitted_at) as leave_submitted_at,
      max(rejoined_at) as rejoined_at
    from raw_dates
    group by public.normalization_safe_date(source_date)
  )
  insert into public.season_registration_date_statuses (
    registration_id,
    activity_date_id,
    is_on_leave,
    leave_submitted_at,
    rejoined_at
  )
  select
    new.id,
    activity_date.id,
    normalized_dates.is_on_leave,
    normalized_dates.leave_submitted_at,
    normalized_dates.rejoined_at
  from normalized_dates
  join public.activity_dates as activity_date
    on activity_date.activity_id = new.activity_id
   and activity_date.activity_date = normalized_dates.activity_date
  where normalized_dates.activity_date is not null
  on conflict (registration_id, activity_date_id) do update
  set is_on_leave = excluded.is_on_leave,
      leave_submitted_at = coalesce(excluded.leave_submitted_at, season_registration_date_statuses.leave_submitted_at),
      rejoined_at = coalesce(excluded.rejoined_at, season_registration_date_statuses.rejoined_at),
      updated_at = now();

  return new;
end;
$$;

-- Backfill activity dates before resolving registrations and leave state.
with raw_dates as (
  select
    activity.id as activity_id,
    public.normalization_safe_date(item.value) as activity_date,
    item.ordinality::integer as sort_order
  from public.activities as activity
  cross join lateral jsonb_array_elements_text(public.normalization_jsonb_array(activity.dates)) with ordinality as item(value, ordinality)
), valid_dates as (
  select activity_id, activity_date, min(sort_order) as sort_order
  from raw_dates
  where activity_date is not null
  group by activity_id, activity_date
)
insert into public.activity_dates (activity_id, activity_date, sort_order, is_active)
select activity_id, activity_date, sort_order, true
from valid_dates
on conflict (activity_id, activity_date) do update
set sort_order = excluded.sort_order,
    is_active = true,
    updated_at = now();

insert into public.normalization_migration_issues (source_table, source_id, source_column, source_value, details)
select
  'activities',
  activity.id::text,
  'dates',
  item.value,
  'Ignored by activity_dates because it is not a valid ISO date.'
from public.activities as activity
cross join lateral jsonb_array_elements_text(public.normalization_jsonb_array(activity.dates)) as item(value)
where public.normalization_safe_date(item.value) is null
on conflict (source_table, source_id, source_column, source_value) do nothing;

update public.registrations as registration
set activity_date_id = activity_date.id
from public.activity_dates as activity_date
where registration.activity_id = activity_date.activity_id
  and registration.activity_date is not null
  and activity_date.activity_date = public.normalization_safe_date(registration.activity_date)
  and registration.activity_date_id is distinct from activity_date.id;

insert into public.normalization_migration_issues (source_table, source_id, source_column, source_value, details)
select
  'registrations',
  registration.id::text,
  'activity_date',
  registration.activity_date,
  'No matching activity date was found; activity_date_id remains null.'
from public.registrations as registration
left join public.activity_dates as activity_date
  on activity_date.activity_id = registration.activity_id
 and activity_date.activity_date = public.normalization_safe_date(registration.activity_date)
where registration.activity_date is not null
  and activity_date.id is null
on conflict (source_table, source_id, source_column, source_value) do nothing;

insert into public.registration_guests (
  registration_id,
  guest_position,
  display_name,
  gender,
  joined_at,
  paid_court,
  paid_ac,
  legacy_payload
)
select
  registration.id,
  item.ordinality::integer - 1,
  nullif(btrim(item.value ->> 'name'), ''),
  case
    when item.value ->> 'gender' in ('male', 'female', 'other') then item.value ->> 'gender'
    else null
  end,
  public.normalization_safe_timestamptz(item.value ->> 'added_at'),
  case lower(coalesce(item.value ->> 'paid_court', '')) when 'true' then true when '1' then true else false end,
  case lower(coalesce(item.value ->> 'paid_ac', '')) when 'true' then true when '1' then true else false end,
  item.value
from public.registrations as registration
cross join lateral jsonb_array_elements(public.normalization_jsonb_array(registration.guests)) with ordinality as item(value, ordinality)
on conflict (registration_id, guest_position) do update
set display_name = excluded.display_name,
    gender = excluded.gender,
    joined_at = excluded.joined_at,
    paid_court = excluded.paid_court,
    paid_ac = excluded.paid_ac,
    legacy_payload = excluded.legacy_payload,
    updated_at = now();

insert into public.registration_cancellation_events (
  registration_id,
  legacy_source,
  legacy_position,
  participant_type,
  display_name,
  picture_url,
  added_by,
  participant_added_at,
  legacy_payload
)
select
  registration.id,
  entries.legacy_source,
  entries.ordinality::integer - 1,
  case when entries.legacy_source = 'cancelled_guests' or entries.value ? 'addedBy' then 'guest' else 'self' end,
  nullif(btrim(entries.value ->> 'name'), ''),
  nullif(btrim(entries.value ->> 'image'), ''),
  nullif(btrim(entries.value ->> 'addedBy'), ''),
  public.normalization_safe_timestamptz(entries.value ->> 'time'),
  entries.value
from public.registrations as registration
cross join lateral (
  select 'cancelled_members'::text as legacy_source, item.value, item.ordinality
  from jsonb_array_elements(public.normalization_jsonb_array(registration.cancelled_members)) with ordinality as item(value, ordinality)
  union all
  select 'cancelled_guests'::text as legacy_source, item.value, item.ordinality
  from jsonb_array_elements(public.normalization_jsonb_array(registration.cancelled_guests)) with ordinality as item(value, ordinality)
) as entries
on conflict (registration_id, legacy_source, legacy_position) do update
set participant_type = excluded.participant_type,
    display_name = excluded.display_name,
    picture_url = excluded.picture_url,
    added_by = excluded.added_by,
    participant_added_at = excluded.participant_added_at,
    legacy_payload = excluded.legacy_payload;

with raw_dates as (
  select registration.id as registration_id, registration.activity_id, leave_date as source_date, true as is_on_leave, null::timestamptz as leave_submitted_at, null::timestamptz as rejoined_at
  from public.registrations as registration
  cross join lateral unnest(coalesce(registration.leave_dates, '{}'::text[])) as leave_date
  where registration.activity_id is not null
    and registration.activity_date is null

  union all

  select registration.id, registration.activity_id, entry.key, false, public.normalization_safe_timestamptz(entry.value), null::timestamptz
  from public.registrations as registration
  cross join lateral jsonb_each_text(public.normalization_jsonb_object(registration.leave_times)) as entry(key, value)
  where registration.activity_id is not null
    and registration.activity_date is null

  union all

  select registration.id, registration.activity_id, entry.key, false, null::timestamptz, public.normalization_safe_timestamptz(entry.value)
  from public.registrations as registration
  cross join lateral jsonb_each_text(public.normalization_jsonb_object(registration.rejoin_times)) as entry(key, value)
  where registration.activity_id is not null
    and registration.activity_date is null
), normalized_dates as (
  select
    registration_id,
    activity_id,
    public.normalization_safe_date(source_date) as activity_date,
    bool_or(is_on_leave) as is_on_leave,
    max(leave_submitted_at) as leave_submitted_at,
    max(rejoined_at) as rejoined_at
  from raw_dates
  group by registration_id, activity_id, public.normalization_safe_date(source_date)
)
insert into public.season_registration_date_statuses (
  registration_id,
  activity_date_id,
  is_on_leave,
  leave_submitted_at,
  rejoined_at
)
select
  normalized_dates.registration_id,
  activity_date.id,
  normalized_dates.is_on_leave,
  normalized_dates.leave_submitted_at,
  normalized_dates.rejoined_at
from normalized_dates
join public.activity_dates as activity_date
  on activity_date.activity_id = normalized_dates.activity_id
 and activity_date.activity_date = normalized_dates.activity_date
where normalized_dates.activity_date is not null
on conflict (registration_id, activity_date_id) do update
set is_on_leave = excluded.is_on_leave,
    leave_submitted_at = excluded.leave_submitted_at,
    rejoined_at = excluded.rejoined_at,
    updated_at = now();

with raw_dates as (
  select registration.id as registration_id, registration.activity_id, leave_date as source_date
  from public.registrations as registration
  cross join lateral unnest(coalesce(registration.leave_dates, '{}'::text[])) as leave_date
  where registration.activity_id is not null
    and registration.activity_date is null

  union

  select registration.id, registration.activity_id, entry.key
  from public.registrations as registration
  cross join lateral jsonb_each_text(public.normalization_jsonb_object(registration.leave_times)) as entry(key, value)
  where registration.activity_id is not null
    and registration.activity_date is null

  union

  select registration.id, registration.activity_id, entry.key
  from public.registrations as registration
  cross join lateral jsonb_each_text(public.normalization_jsonb_object(registration.rejoin_times)) as entry(key, value)
  where registration.activity_id is not null
    and registration.activity_date is null
)
insert into public.normalization_migration_issues (source_table, source_id, source_column, source_value, details)
select
  'registrations',
  raw_dates.registration_id::text,
  'leave_dates',
  raw_dates.source_date,
  case
    when public.normalization_safe_date(raw_dates.source_date) is null then 'Ignored because the leave/rejoin key is not a valid ISO date.'
    else 'No matching activity date was found; normalized leave state was not created.'
  end
from raw_dates
left join public.activity_dates as activity_date
  on activity_date.activity_id = raw_dates.activity_id
 and activity_date.activity_date = public.normalization_safe_date(raw_dates.source_date)
where public.normalization_safe_date(raw_dates.source_date) is null
   or activity_date.id is null
on conflict (source_table, source_id, source_column, source_value) do nothing;

drop trigger if exists registrations_set_activity_date_reference on public.registrations;
create trigger registrations_set_activity_date_reference
before insert or update of activity_id, activity_date on public.registrations
for each row
execute function public.sync_registration_activity_date_reference();

drop trigger if exists registrations_sync_normalized_guests on public.registrations;
create trigger registrations_sync_normalized_guests
after insert or update of guests on public.registrations
for each row
execute function public.sync_registration_guests_from_legacy_json();

drop trigger if exists registrations_sync_normalized_cancellations on public.registrations;
create trigger registrations_sync_normalized_cancellations
after insert or update of cancelled_members, cancelled_guests on public.registrations
for each row
execute function public.sync_registration_cancellation_events_from_legacy_json();

drop trigger if exists registrations_sync_normalized_session_statuses on public.registrations;
create trigger registrations_sync_normalized_session_statuses
after insert or update of activity_id, activity_date, leave_dates, leave_times, rejoin_times on public.registrations
for each row
execute function public.sync_season_registration_date_statuses_from_legacy();

drop trigger if exists activities_sync_normalized_sessions on public.activities;
create trigger activities_sync_normalized_sessions
after insert or update of dates on public.activities
for each row
execute function public.sync_activity_dates_from_legacy_dates();
